### ISSUE TITLE
Can not bind object to error.meta

### ISSUE THREAD

**Issue by orangemi** [sailxjx/err1st#4]
`v0.2.5` works but `v0.2.6` doesn't. Code like this:
```
Error.meta({
  some_error: {
    code: 100,
    status: 404,
    renderHtml: true
  }
})
...

err = new Err1st('some_error')
console.log(err.meta.renderHtml) // undefined
```

I suggest user can bind other key to error.meta for further operation not only locales.

**Comment by sailxjx** [comment]
除了 code 和 status 这些关键字外，其他属性都当成 _locales 多语言选项保存下来了，可以用这种方式调用
`console.log(err.meta._locales.renderHtml)`

**Comment by orangemi** [comment]
嗯，可以这样用，我觉得不太合适。觉得meta上应该可以绑自己的东西。

**Comment by sailxjx** [comment]
改了，自定义的字段会在 meta 上留下来

**Comment by orangemi** [comment]
great job~
